[package]
name = "bsdiff"
version = "0.1.0"
authors = ["pieterjan.briers@gmail.com"]
readme = "README.md"
keywords = ["bsdiff", "bspatch", "diff"]
license = "BSD-2-Clause"

[dependencies]
libc = "0.2.24"